# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py{36,39,311,312}

[coverage:run]
omit = none

[flake8]
exclude = .ipynb_checkpoints
ignore = E501,W504,W503

[testenv]
# install pytest in the virtualenv where commands will be executed
deps =
    pytest
    flake8

commands =
    # NOTE: you can run any command line tool here - not just tests
    flake8 src/PseudoNetCDF
    python -m pytest -v src/PseudoNetCDF

[gh-actions]
python = 
  3.6: py36
  3.9: py39
  3.11: py311
  3.12: py312
