name: AltTests
on:
  workflow_dispatch:

permissions:
    contents: write
jobs:
  tests:
    name: ${{ matrix.os }} py${{ matrix.python-version }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        # Bookend python versions
        python-version: ["3.9", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions pytest flake8 coverage
      - name: tox
        run: tox
